function ResponseComparison({
  generic,
  enhanced
}: any) {

  return (

    <div className="
      bg-white
      rounded-2xl
      shadow-md
      p-6
      mb-8
    ">

      <h2 className="
        text-2xl
        font-bold
        mb-6
      ">

        Generic AI vs Safety-Enhanced AI

      </h2>

      <div className="
        grid
        grid-cols-1
        lg:grid-cols-2
        gap-6
      ">

        <div className="
          bg-gray-100
          rounded-2xl
          p-5
          border
          border-gray-200
        ">

          <div className="
            flex
            items-center
            justify-between
            mb-4
          ">

            <h3 className="
              text-xl
              font-bold
            ">

              Generic AI

            </h3>

            <span className="
              bg-gray-300
              text-gray-800
              text-xs
              px-3
              py-1
              rounded-full
            ">

              Unconstrained

            </span>

          </div>

          <div className="
            whitespace-pre-wrap
            text-gray-700
            leading-7
          ">

            {
              generic ||

              "Generic AI response unavailable."
            }

          </div>

        </div>

        <div className="
          bg-blue-50
          rounded-2xl
          p-5
          border
          border-blue-200
        ">

          <div className="
            flex
            items-center
            justify-between
            mb-4
          ">

            <h3 className="
              text-xl
              font-bold
              text-blue-900
            ">

              Safety-Enhanced AI

            </h3>

            <span className="
              bg-blue-200
              text-blue-900
              text-xs
              px-3
              py-1
              rounded-full
            ">

              Deterministic + AI

            </span>

          </div>

          <div className="
            whitespace-pre-wrap
            text-gray-800
            leading-7
          ">

            {
              enhanced ||

              "Enhanced AI response unavailable."
            }

          </div>

        </div>

      </div>

      <div className="
        mt-6
        bg-yellow-50
        border
        border-yellow-200
        rounded-xl
        p-4
      ">

        <p className="
          text-sm
          text-yellow-800
          leading-6
        ">

          The Safety-Enhanced AI response uses deterministic
          clinical safety constraints generated by the
          interaction engine, allergy engine, and renal
          dosing checks before sending context to the LLM.

        </p>

      </div>

    </div>
  );
}

export default ResponseComparison;